import cbg
import ctypes
import sys
import argparse

from definitions import define

parser = argparse.ArgumentParser()
parser.add_argument('-l', '--lang', type=str, default='en',
                    required=False, choices=['ja', 'en'])
args = parser.parse_args()

bindingGenerator = cbg.BindingGeneratorCSharp(define, args.lang)
bindingGenerator.output_path = 'tests/results/CSharp/AutoGeneratedCoreBindings.cs'
bindingGenerator.dll_name = 'CoreLib'
bindingGenerator.namespace = 'HelloWorld'
bindingGenerator.generate()

# generate
sharedObjectGenerator = cbg.SharedObjectGenerator(define)

sharedObjectGenerator.header = '''
#include "HelloWorld.h"
'''

sharedObjectGenerator.func_name_create_and_add_shared_ptr = 'HelloWorld::CreateAndAddSharedPtr'
sharedObjectGenerator.func_name_add_and_get_shared_ptr = 'HelloWorld::AddAndGetSharedPtr'

sharedObjectGenerator.output_path = 'tests/results/so/AutoGeneratedCoreWrapper.cpp'
sharedObjectGenerator.generate()
