from cbg import *

definition = Definition()

with Class('SimpleClass') as simple_class:
    definition.classes.append(simple_class)
    simple_class.brief = "単純なクラス"
    simple_class.namespace = 'CoreSample'
    with simple_class.add_constructor() as func:
        func.brief = "コンストラクタ"

wrapper_generator = WrapperGenerator()
wrapper_generator.definition = definition
wrapper_generator.header = '#include "CoreSample.h"'
wrapper_generator.output_path = './tests/results/WrapperCpp/AutoGeneratedWrapper.cpp'
wrapper_generator.generate()