import ctypes, sys, argparse, os

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import cbg
from definitions import define, define_cpp, ReplaceStructA

parser = argparse.ArgumentParser()
parser.add_argument('-l', '--lang', type=str, default='en', required=False, choices=['ja', 'en'])
args = parser.parse_args()

# generate
bindingGenerator = cbg.BindingGeneratorRust(define, [], args.lang)
bindingGenerator.output_path = 'tests/results/rust/src/auto_generated_core_bindings.rs'
bindingGenerator.dll_name = 'CoreLib'
bindingGenerator.module = ''
bindingGenerator.structsReplaceMap = {
    ReplaceStructA : "crate::ReplaceStruct<f32>"
}
bindingGenerator.struct_module_name = 'crate::structs'
bindingGenerator.generate()

# sharedObjectGenerator = cbg.SharedObjectGenerator(define, [])

# sharedObjectGenerator.header = '''
# #include "HelloWorld.h"
# '''

# sharedObjectGenerator.func_name_create_and_add_shared_ptr = 'HelloWorld::CreateAndAddSharedPtr'
# sharedObjectGenerator.func_name_add_and_get_shared_ptr = 'HelloWorld::AddAndGetSharedPtr'

# sharedObjectGenerator.output_path = 'tests/results/so/AutoGeneratedCoreWrapper.cpp'
# sharedObjectGenerator.generate()

# generate
dep = cbg.DefineDependency()
dep.namespace = 'cbg_rust::prelude'
dep.define = define

bindingGenerator_cpp = cbg.BindingGeneratorRust(define_cpp, [dep], args.lang)
bindingGenerator_cpp.output_path = 'tests/results/rust_cpp/src/auto_generated_core_bindings.rs'
bindingGenerator_cpp.dll_name = 'cplusplus'
bindingGenerator_cpp.module = ''
bindingGenerator.structsReplaceMap = {
    ReplaceStructA : "crate::ReplaceStruct<f32>"
}
bindingGenerator_cpp.struct_module_name = 'crate::structs'
bindingGenerator_cpp.generate()

# sharedObjectCppGenerator = cbg.SharedObjectGenerator(define_cpp, [dep])

# sharedObjectCppGenerator.header = '''
# #include "cplusplus.h"
# '''

# sharedObjectCppGenerator.func_name_create_and_add_shared_ptr = 'HelloWorldCpp::CreateAndAddSharedPtr'
# sharedObjectCppGenerator.func_name_add_and_get_shared_ptr = 'HelloWorldCpp::AddAndGetSharedPtr'

# sharedObjectCppGenerator.output_path = 'tests/results/cplusplus/AutoGeneratedCoreWrapper.cpp'
# sharedObjectCppGenerator.generate()
